[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VUE_APP_API_LIVE="https://staging.gettonote.com/api/v1/"
  VUE_APP_URL_WEBSITE="https://www.gettonote.com"
  VUE_APP_URL_AUTH_LIVE="https://gettonote-user-new.netlify.app"
  VUE_APP_URL_AUTH_FORGOT_PASSWORD_LIVE="https://gettonote-user-new.netlify.app/forgot-password"
  VUE_APP_URL_SIGN_LINK="https://tonote-doc-link.netlify.app"
  VUE_APP_URL_USER_UPGRADE_LIVE="https://gettonote-user-new.netlify.app/admin/settings/?tab=billing"
  VUE_APP_TAWK_PROPERTY_ID="6257cf987b967b11798ab0e5 "
  VUE_APP_TAWK_WIDGET_ID="1g0jg5rf5"